### PR TITLE
TCA-480 - replace learn.freecodecamp.org links with the platformui links

### PR DESCRIPTION
**Pull request by vas3a**
> https://topcoder.atlassian.net/browse/TCA-480
> 
> Replace the FCC courses links that are located in the lesson content with links pointed to platform-ui.

-- this PR updates **learn.freecodecamp.org** links

### CODE REVIEW

**Review by testflyjets — APPROVED** [review]

**Review by brooketopcoder — APPROVED** [review]
@vas3a Should we remove the external link handling from the Platform UI? I don't want anyone to think they have to maintain it if a new link type is found.

**Comment by vas3a** [comment]
@brooketopcoder do you mean the url handling in `client/src/components/layouts/tc-integration.tsx` ?

**Comment by brooketopcoder** [comment]
@vas3a Yes, that's what I meant. I forgot that it's actually in the FCC app.

**Comment by vas3a** [comment]
@brooketopcoder thanks for catching that up for me!

Upon removal and closer inspection to the handler, I found out that I didn't replace the urls that just started with "/learn". I replaced all urls, I think this is complete now.

**Review by brooketopcoder — APPROVED** [review]

**Pull request merged**
