### PR TITLE
TCA-480 - replace fcc links located in the lesson content

### PR DESCRIPTION
**Pull request by vas3a**
https://topcoder.atlassian.net/browse/TCA-480

Replace the FCC courses links that are located in the lesson content with links pointed to platform-ui.

Example lesson that has a link to another course:

https://platform-ui.topcoder-dev.com/learn/freeCodeCamp/quality-assurance/quality-assurance-and-testing-with-chai/use-assert-isok-and-assert-isnotok

image

### CODE REVIEW

**Review by testflyjets — COMMENTED** [review]
These changed links all point to topcoder.com -- how's this going to work in the dev environment?

**Comment by vas3a** [comment]
@testflyjets it will just redirect to the prod urls. Not sure if we can modify the urls inside the lesson content to be environment aware, should this be a concern?

**Comment by testflyjets** [comment]
> @testflyjets it will just redirect to the prod urls. Not sure if we can modify the urls inside the lesson content to be environment aware, should this be a concern?

If the user doesn't have to follow the link to complete the challenge then it most likely won't matter that links in dev point to prod. All good.

**Review by testflyjets — APPROVED** [review]

**Comment by vas3a** [comment]
Yup. these are just suggestions, they don't matter for the challenge itself.

**Pull request merged**
